
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DATA_WD = 8;
  public static final int IP = 13;
  public static final int TIME = 12;
  public static final int DATE = 11;
  public static final int SERVER = 3;
  public static final int MP3LIST = 2;
  public static final int CM = 4;
  public static final int S = 5;
  public static final int FILENAME = 10;
  public static final int EOF = 0;
  public static final int TIME_WD = 9;
  public static final int KBITSEC = 7;
  public static final int error = 1;
  public static final int COL = 6;
  public static final int UINT = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MP3LIST",
  "SERVER",
  "CM",
  "S",
  "COL",
  "KBITSEC",
  "DATA_WD",
  "TIME_WD",
  "FILENAME",
  "DATE",
  "TIME",
  "IP",
  "UINT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("DATA_WD");
		TT[13]=new String("IP");
		TT[12]=new String("TIME");
		TT[11]=new String("DATE");
		TT[3]=new String("SERVER");
		TT[2]=new String("MP3LIST");
		TT[4]=new String("CM");
		TT[5]=new String("S");
		TT[10]=new String("FILENAME");
		TT[0]=new String("EOF");
		TT[9]=new String("TIME_WD");
		TT[7]=new String("KBITSEC");
		TT[1]=new String("error");
		TT[6]=new String("COL");
		TT[14]=new String("UINT");
	}
public String getTT(int i){return TT[i];}
}

