
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 8;
  public static final int OR = 9;
  public static final int S = 5;
  public static final int RO = 11;
  public static final int NOT = 10;
  public static final int FI = 16;
  public static final int TRUE = 13;
  public static final int IF = 15;
  public static final int ID = 22;
  public static final int DO = 17;
  public static final int RC = 12;
  public static final int EOF = 0;
  public static final int OR_WORD = 21;
  public static final int FALSE = 14;
  public static final int SEP = 6;
  public static final int PRINT = 18;
  public static final int error = 1;
  public static final int EQ = 7;
  public static final int QSTRING = 23;
  public static final int AND_WORD = 20;
  public static final int DONE = 19;
  public static final int TK3 = 4;
  public static final int TK2 = 3;
  public static final int TK1 = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK1",
  "TK2",
  "TK3",
  "S",
  "SEP",
  "EQ",
  "AND",
  "OR",
  "NOT",
  "RO",
  "RC",
  "TRUE",
  "FALSE",
  "IF",
  "FI",
  "DO",
  "PRINT",
  "DONE",
  "AND_WORD",
  "OR_WORD",
  "ID",
  "QSTRING"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("AND");
		TT[9]=new String("OR");
		TT[5]=new String("S");
		TT[11]=new String("RO");
		TT[10]=new String("NOT");
		TT[16]=new String("FI");
		TT[13]=new String("TRUE");
		TT[15]=new String("IF");
		TT[22]=new String("ID");
		TT[17]=new String("DO");
		TT[12]=new String("RC");
		TT[0]=new String("EOF");
		TT[21]=new String("OR_WORD");
		TT[14]=new String("FALSE");
		TT[6]=new String("SEP");
		TT[18]=new String("PRINT");
		TT[1]=new String("error");
		TT[7]=new String("EQ");
		TT[23]=new String("QSTRING");
		TT[20]=new String("AND_WORD");
		TT[19]=new String("DONE");
		TT[4]=new String("TK3");
		TT[3]=new String("TK2");
		TT[2]=new String("TK1");
	}
public String getTT(int i){return TT[i];}
}

