
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 5;
  public static final int SO = 27;
  public static final int UINT = 35;
  public static final int LITERS = 13;
  public static final int S = 6;
  public static final int HECTOLITERS = 14;
  public static final int FZ = 32;
  public static final int SC = 28;
  public static final int INIT = 7;
  public static final int TK3 = 4;
  public static final int TK2 = 3;
  public static final int VOLUME = 12;
  public static final int STAR = 16;
  public static final int TK1 = 2;
  public static final int CM = 9;
  public static final int KILOGRAMS = 11;
  public static final int OBJECT = 21;
  public static final int WEIGHT = 8;
  public static final int RO = 17;
  public static final int PLUS = 15;
  public static final int MIN = 19;
  public static final int IF = 33;
  public static final int ATTRIBUTES = 22;
  public static final int DOT = 23;
  public static final int ID = 34;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RC = 18;
  public static final int ADD = 30;
  public static final int MOD = 29;
  public static final int BO = 25;
  public static final int EQ = 24;
  public static final int GRAMS = 10;
  public static final int BC = 26;
  public static final int MAX = 20;
  public static final int SUB = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK1",
  "TK2",
  "TK3",
  "SEP",
  "S",
  "INIT",
  "WEIGHT",
  "CM",
  "GRAMS",
  "KILOGRAMS",
  "VOLUME",
  "LITERS",
  "HECTOLITERS",
  "PLUS",
  "STAR",
  "RO",
  "RC",
  "MIN",
  "MAX",
  "OBJECT",
  "ATTRIBUTES",
  "DOT",
  "EQ",
  "BO",
  "BC",
  "SO",
  "SC",
  "MOD",
  "ADD",
  "SUB",
  "FZ",
  "IF",
  "ID",
  "UINT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[5]=new String("SEP");
		TT[27]=new String("SO");
		TT[35]=new String("UINT");
		TT[13]=new String("LITERS");
		TT[6]=new String("S");
		TT[14]=new String("HECTOLITERS");
		TT[32]=new String("FZ");
		TT[28]=new String("SC");
		TT[7]=new String("INIT");
		TT[4]=new String("TK3");
		TT[3]=new String("TK2");
		TT[12]=new String("VOLUME");
		TT[16]=new String("STAR");
		TT[2]=new String("TK1");
		TT[9]=new String("CM");
		TT[11]=new String("KILOGRAMS");
		TT[21]=new String("OBJECT");
		TT[8]=new String("WEIGHT");
		TT[17]=new String("RO");
		TT[15]=new String("PLUS");
		TT[19]=new String("MIN");
		TT[33]=new String("IF");
		TT[22]=new String("ATTRIBUTES");
		TT[23]=new String("DOT");
		TT[34]=new String("ID");
		TT[0]=new String("EOF");
		TT[1]=new String("error");
		TT[18]=new String("RC");
		TT[30]=new String("ADD");
		TT[29]=new String("MOD");
		TT[25]=new String("BO");
		TT[24]=new String("EQ");
		TT[10]=new String("GRAMS");
		TT[26]=new String("BC");
		TT[20]=new String("MAX");
		TT[31]=new String("SUB");
	}
public String getTT(int i){return TT[i];}
}

