
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C = 9;
  public static final int IP = 13;
  public static final int DATE = 11;
  public static final int TIME = 5;
  public static final int HOUR = 10;
  public static final int SERVER = 4;
  public static final int NUMBER = 14;
  public static final int SONG = 12;
  public static final int CM = 8;
  public static final int DATA = 6;
  public static final int S = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int KBS = 3;
  public static final int START = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "START",
  "KBS",
  "SERVER",
  "TIME",
  "DATA",
  "S",
  "CM",
  "C",
  "HOUR",
  "DATE",
  "SONG",
  "IP",
  "NUMBER"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[9]=new String("C");
		TT[13]=new String("IP");
		TT[11]=new String("DATE");
		TT[5]=new String("TIME");
		TT[10]=new String("HOUR");
		TT[4]=new String("SERVER");
		TT[14]=new String("NUMBER");
		TT[12]=new String("SONG");
		TT[8]=new String("CM");
		TT[6]=new String("DATA");
		TT[7]=new String("S");
		TT[0]=new String("EOF");
		TT[1]=new String("error");
		TT[3]=new String("KBS");
		TT[2]=new String("START");
	}
public String getTT(int i){return TT[i];}
}

