
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK1 = 2;
  public static final int EUROKG = 9;
  public static final int SC = 8;
  public static final int QSTRING = 13;
  public static final int CM = 10;
  public static final int S = 4;
  public static final int EOF = 0;
  public static final int SEP = 5;
  public static final int DOT = 11;
  public static final int REAL = 15;
  public static final int SO = 7;
  public static final int error = 1;
  public static final int COL = 6;
  public static final int KG = 12;
  public static final int UINT = 14;
  public static final int TK2 = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK1",
  "TK2",
  "S",
  "SEP",
  "COL",
  "SO",
  "SC",
  "EUROKG",
  "CM",
  "DOT",
  "KG",
  "QSTRING",
  "UINT",
  "REAL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[2]=new String("TK1");
		TT[9]=new String("EUROKG");
		TT[8]=new String("SC");
		TT[13]=new String("QSTRING");
		TT[10]=new String("CM");
		TT[4]=new String("S");
		TT[0]=new String("EOF");
		TT[5]=new String("SEP");
		TT[11]=new String("DOT");
		TT[15]=new String("REAL");
		TT[7]=new String("SO");
		TT[1]=new String("error");
		TT[6]=new String("COL");
		TT[12]=new String("KG");
		TT[14]=new String("UINT");
		TT[3]=new String("TK2");
	}
public String getTT(int i){return TT[i];}
}

