
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UPDATE_WD = 17;
  public static final int MAJ = 18;
  public static final int CM = 8;
  public static final int SUM = 12;
  public static final int S = 5;
  public static final int SPEED_WD = 10;
  public static final int SO = 15;
  public static final int EOF = 0;
  public static final int HEIGHT_WD = 9;
  public static final int SEP = 6;
  public static final int error = 1;
  public static final int COND_WD = 14;
  public static final int EQ = 11;
  public static final int UINT = 20;
  public static final int SC = 16;
  public static final int DONE = 19;
  public static final int TK3 = 4;
  public static final int MUL = 13;
  public static final int TK2 = 3;
  public static final int TK1 = 2;
  public static final int INIT_WD = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK1",
  "TK2",
  "TK3",
  "S",
  "SEP",
  "INIT_WD",
  "CM",
  "HEIGHT_WD",
  "SPEED_WD",
  "EQ",
  "SUM",
  "MUL",
  "COND_WD",
  "SO",
  "SC",
  "UPDATE_WD",
  "MAJ",
  "DONE",
  "UINT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[17]=new String("UPDATE_WD");
		TT[18]=new String("MAJ");
		TT[8]=new String("CM");
		TT[12]=new String("SUM");
		TT[5]=new String("S");
		TT[10]=new String("SPEED_WD");
		TT[15]=new String("SO");
		TT[0]=new String("EOF");
		TT[9]=new String("HEIGHT_WD");
		TT[6]=new String("SEP");
		TT[1]=new String("error");
		TT[14]=new String("COND_WD");
		TT[11]=new String("EQ");
		TT[20]=new String("UINT");
		TT[16]=new String("SC");
		TT[19]=new String("DONE");
		TT[4]=new String("TK3");
		TT[13]=new String("MUL");
		TT[3]=new String("TK2");
		TT[2]=new String("TK1");
		TT[7]=new String("INIT_WD");
	}
public String getTT(int i){return TT[i];}
}

