
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 15;
  public static final int OR = 16;
  public static final int CM = 21;
  public static final int T = 18;
  public static final int S = 5;
  public static final int RO = 13;
  public static final int NOT = 17;
  public static final int ID = 22;
  public static final int WITH = 9;
  public static final int RC = 14;
  public static final int F = 19;
  public static final int SO = 10;
  public static final int EOF = 0;
  public static final int CMP = 8;
  public static final int SEP = 6;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int EQ = 7;
  public static final int QSTRING = 23;
  public static final int FZFUNCTION = 20;
  public static final int SC = 11;
  public static final int TK3 = 4;
  public static final int TK2 = 3;
  public static final int TK1 = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK1",
  "TK2",
  "TK3",
  "S",
  "SEP",
  "EQ",
  "CMP",
  "WITH",
  "SO",
  "SC",
  "PRINT",
  "RO",
  "RC",
  "AND",
  "OR",
  "NOT",
  "T",
  "F",
  "FZFUNCTION",
  "CM",
  "ID",
  "QSTRING"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[15]=new String("AND");
		TT[16]=new String("OR");
		TT[21]=new String("CM");
		TT[18]=new String("T");
		TT[5]=new String("S");
		TT[13]=new String("RO");
		TT[17]=new String("NOT");
		TT[22]=new String("ID");
		TT[9]=new String("WITH");
		TT[14]=new String("RC");
		TT[19]=new String("F");
		TT[10]=new String("SO");
		TT[0]=new String("EOF");
		TT[8]=new String("CMP");
		TT[6]=new String("SEP");
		TT[12]=new String("PRINT");
		TT[1]=new String("error");
		TT[7]=new String("EQ");
		TT[23]=new String("QSTRING");
		TT[20]=new String("FZFUNCTION");
		TT[11]=new String("SC");
		TT[4]=new String("TK3");
		TT[3]=new String("TK2");
		TT[2]=new String("TK1");
	}
public String getTT(int i){return TT[i];}
}

