
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 16;
  public static final int SO = 14;
  public static final int S = 12;
  public static final int L = 25;
  public static final int FZ = 27;
  public static final int SC = 13;
  public static final int INT = 3;
  public static final int INIT = 20;
  public static final int G = 23;
  public static final int VOLUME = 22;
  public static final int STAR = 15;
  public static final int TOK3 = 19;
  public static final int CM = 6;
  public static final int TOK2 = 18;
  public static final int TOK1 = 17;
  public static final int OBJECT = 30;
  public static final int WEIGHT = 21;
  public static final int RO = 11;
  public static final int PLUS = 9;
  public static final int MIN = 29;
  public static final int IF = 32;
  public static final int ATTRIBUTES = 31;
  public static final int DOT = 7;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RC = 10;
  public static final int ADD = 34;
  public static final int MOD = 33;
  public static final int BO = 5;
  public static final int EQ = 8;
  public static final int HL = 26;
  public static final int BC = 4;
  public static final int KG = 24;
  public static final int MAX = 28;
  public static final int SUB = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INT",
  "BC",
  "BO",
  "CM",
  "DOT",
  "EQ",
  "PLUS",
  "RC",
  "RO",
  "S",
  "SC",
  "SO",
  "STAR",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "INIT",
  "WEIGHT",
  "VOLUME",
  "G",
  "KG",
  "L",
  "HL",
  "FZ",
  "MAX",
  "MIN",
  "OBJECT",
  "ATTRIBUTES",
  "IF",
  "MOD",
  "ADD",
  "SUB"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[16]=new String("SEP");
		TT[14]=new String("SO");
		TT[12]=new String("S");
		TT[25]=new String("L");
		TT[27]=new String("FZ");
		TT[13]=new String("SC");
		TT[3]=new String("INT");
		TT[20]=new String("INIT");
		TT[23]=new String("G");
		TT[22]=new String("VOLUME");
		TT[15]=new String("STAR");
		TT[19]=new String("TOK3");
		TT[6]=new String("CM");
		TT[18]=new String("TOK2");
		TT[17]=new String("TOK1");
		TT[30]=new String("OBJECT");
		TT[21]=new String("WEIGHT");
		TT[11]=new String("RO");
		TT[9]=new String("PLUS");
		TT[29]=new String("MIN");
		TT[32]=new String("IF");
		TT[31]=new String("ATTRIBUTES");
		TT[7]=new String("DOT");
		TT[2]=new String("ID");
		TT[0]=new String("EOF");
		TT[1]=new String("error");
		TT[10]=new String("RC");
		TT[34]=new String("ADD");
		TT[33]=new String("MOD");
		TT[5]=new String("BO");
		TT[8]=new String("EQ");
		TT[26]=new String("HL");
		TT[4]=new String("BC");
		TT[24]=new String("KG");
		TT[28]=new String("MAX");
		TT[35]=new String("SUB");
	}
public String getTT(int i){return TT[i];}
}

