GET http://localhost:3000/api/films

###

GET http://localhost:3000/api/filters

###

GET http://localhost:3000/api/films?filter=filter-unseen

###

GET http://localhost:3000/api/films/7

###
POST http://localhost:3000/api/films/new
Content-Type: application/json

{
  "title": "Rambo",
  "favorite": 0,
  "watchdate": "2021-05-25",
  "rating": 2,
  "user": 1
}

###
PUT http://localhost:3000/api/films/1/edit 
Content-Type: application/json

{
    "title": "Pulp Fiction",
    "favorite" : 1,
    "watchdate": "2023-04-30",
    "rating" : 5,
    "user" : 1
}


###
PUT http://localhost:3000/api/films/5/rating
Content-Type: application/json

{
     "rating" : 3
}

###
PUT http://localhost:3000/api/films/3/favorite
Content-Type: application/json

{
    "favorite": 1
}

###
DELETE http://localhost:3000/api/films/6/delete