
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\037\000\002\002\004\000\002\002\005\000\002\003" +
    "\003\000\002\003\006\000\002\003\011\000\002\004\005" +
    "\000\002\004\005\000\002\004\002\000\002\005\005\000" +
    "\002\005\002\000\002\007\005\000\002\007\004\000\002" +
    "\006\003\000\002\006\003\000\002\010\006\000\002\011" +
    "\005\000\002\014\005\000\002\014\005\000\002\014\004" +
    "\000\002\014\005\000\002\014\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\006\000\002\015\005\000\002" +
    "\015\003\000\002\012\005\000\002\012\004\000\002\016" +
    "\002\000\002\017\002\000\002\013\011" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\012\004\ufffa\005\ufffa\006\ufffa\022\ufffa\001" +
    "\002\000\012\004\072\005\071\006\070\022\uffff\001\002" +
    "\000\004\002\067\001\002\000\004\022\007\001\002\000" +
    "\010\002\ufff8\010\011\030\010\001\002\000\004\007\064" +
    "\001\002\000\016\017\026\020\032\024\027\025\031\026" +
    "\024\030\025\001\002\000\010\002\ufff4\010\ufff4\030\ufff4" +
    "\001\002\000\006\010\011\030\010\001\002\000\010\002" +
    "\ufff5\010\ufff5\030\ufff5\001\002\000\004\002\000\001\002" +
    "\000\006\010\011\030\010\001\002\000\010\002\ufff9\010" +
    "\011\030\010\001\002\000\006\010\011\030\010\001\002" +
    "\000\010\002\ufff6\010\ufff6\030\ufff6\001\002\000\006\010" +
    "\011\030\010\001\002\000\010\002\ufff7\010\ufff7\030\ufff7" +
    "\001\002\000\004\020\056\001\002\000\020\011\uffeb\012" +
    "\uffeb\015\uffeb\016\uffeb\021\uffeb\023\uffeb\027\uffeb\001\002" +
    "\000\016\017\026\020\032\024\027\025\031\026\024\030" +
    "\025\001\002\000\020\011\uffed\012\uffed\015\uffed\016\uffed" +
    "\021\uffed\023\uffed\027\uffed\001\002\000\010\011\uffe4\015" +
    "\034\016\036\001\002\000\020\011\uffec\012\uffec\015\uffec" +
    "\016\uffec\021\uffec\023\uffec\027\uffec\001\002\000\016\017" +
    "\026\020\032\024\027\025\031\026\024\030\025\001\002" +
    "\000\010\015\034\016\036\021\035\001\002\000\016\017" +
    "\026\020\032\024\027\025\031\026\024\030\025\001\002" +
    "\000\020\011\uffee\012\uffee\015\uffee\016\uffee\021\uffee\023" +
    "\uffee\027\uffee\001\002\000\016\017\026\020\032\024\027" +
    "\025\031\026\024\030\025\001\002\000\020\011\ufff0\012" +
    "\ufff0\015\034\016\ufff0\021\ufff0\023\ufff0\027\ufff0\001\002" +
    "\000\020\011\ufff1\012\ufff1\015\ufff1\016\ufff1\021\ufff1\023" +
    "\ufff1\027\ufff1\001\002\000\012\002\ufff2\010\ufff2\011\uffe5" +
    "\030\ufff2\001\002\000\004\011\043\001\002\000\016\017" +
    "\026\020\032\024\027\025\031\026\024\030\025\001\002" +
    "\000\012\002\uffe6\010\uffe6\011\uffe6\030\uffe6\001\002\000" +
    "\010\012\046\015\034\016\036\001\002\000\004\013\047" +
    "\001\002\000\004\031\050\001\002\000\004\023\051\001" +
    "\002\000\004\014\052\001\002\000\012\002\uffe3\010\uffe3" +
    "\011\uffe3\030\uffe3\001\002\000\004\011\043\001\002\000" +
    "\012\002\uffe7\010\uffe7\011\uffe7\030\uffe7\001\002\000\020" +
    "\011\uffef\012\uffef\015\uffef\016\uffef\021\uffef\023\uffef\027" +
    "\uffef\001\002\000\016\017\026\020\032\024\027\025\031" +
    "\026\024\030\025\001\002\000\006\021\062\027\061\001" +
    "\002\000\012\015\034\016\036\021\uffe8\027\uffe8\001\002" +
    "\000\016\017\026\020\032\024\027\025\031\026\024\030" +
    "\025\001\002\000\020\011\uffea\012\uffea\015\uffea\016\uffea" +
    "\021\uffea\023\uffea\027\uffea\001\002\000\012\015\034\016" +
    "\036\021\uffe9\027\uffe9\001\002\000\016\017\026\020\032" +
    "\024\027\025\031\026\024\030\025\001\002\000\010\015" +
    "\034\016\036\023\066\001\002\000\010\002\ufff3\010\ufff3" +
    "\030\ufff3\001\002\000\004\002\001\001\002\000\004\023" +
    "\101\001\002\000\004\023\074\001\002\000\004\023\073" +
    "\001\002\000\012\004\ufffc\005\ufffc\006\ufffc\022\ufffc\001" +
    "\002\000\012\004\ufffa\005\ufffa\006\ufffa\022\ufffa\001\002" +
    "\000\012\004\072\005\076\006\070\022\ufffe\001\002\000" +
    "\004\023\077\001\002\000\010\004\ufffa\006\ufffa\022\ufffa" +
    "\001\002\000\010\004\072\006\070\022\ufffd\001\002\000" +
    "\012\004\ufffb\005\ufffb\006\ufffb\022\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\010\002\004\003\005\004\003\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\005\014\006\012\010\013\011\011\001\001\000\002\001" +
    "\001\000\004\014\027\001\001\000\002\001\001\000\010" +
    "\006\015\010\013\011\011\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\006\017\007\016\010\013\011\011" +
    "\001\001\000\010\006\021\010\013\011\011\001\001\000" +
    "\010\006\020\010\013\011\011\001\001\000\002\001\001" +
    "\000\010\006\022\010\013\011\011\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\054" +
    "\001\001\000\002\001\001\000\006\012\040\017\041\001" +
    "\001\000\002\001\001\000\004\014\032\001\001\000\002" +
    "\001\001\000\004\014\037\001\001\000\002\001\001\000" +
    "\004\014\036\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\016\052\001\001\000\004\013\043\001\001\000" +
    "\004\014\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\013\053\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\014\057\015" +
    "\056\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\062\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\074\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\077\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap<String, Boolean>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap<String, Boolean> table;

    public void report_error(String message, Object info){
        StringBuffer m = new StringBuffer(message);
        if (info instanceof Symbol){
            if(((Symbol)info).left != 1 && ((Symbol)info).right != 1){
                if(((Symbol)info).left != -1 && ((Symbol)info).right != -1){
                    int line = (((Symbol)info).left) + 1;
                    int column = (((Symbol)info).right) + 1;
                    m.append("(line" + line + "column " + column + ")");
                }
            }
            System.err.println(m);
        }
    }

     // Return semantic value of symbol in position (position)
    public Object stack(int position) {
        return (((Symbol)stack.elementAt(tos+position)).value);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= PROG EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // PROG ::= header_sec SEP command_sec 
            { parser.Tree.reduce(3,"PROG",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PROG",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // header_sec ::= tok1_tok3_maybe 
            { parser.Tree.reduce(1,"header_sec",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header_sec",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // header_sec ::= tok1_tok3_maybe TK2 S tok1_tok3_maybe 
            { parser.Tree.reduce(4,"header_sec",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header_sec",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // header_sec ::= tok1_tok3_maybe TK2 S tok1_tok3_maybe TK2 S tok1_tok3_maybe 
            { parser.Tree.reduce(7,"header_sec",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header_sec",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // tok1_tok3_maybe ::= tok1_tok3_maybe TK1 S 
            { parser.Tree.reduce(3,"tok1_tok3_maybe",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tok1_tok3_maybe",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // tok1_tok3_maybe ::= tok1_tok3_maybe TK3 S 
            { parser.Tree.reduce(3,"tok1_tok3_maybe",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tok1_tok3_maybe",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // tok1_tok3_maybe ::= 
            { parser.Tree.reduce(0,"tok1_tok3_maybe",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tok1_tok3_maybe",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // command_sec ::= cmd cmd more_cmd 
            { parser.Tree.reduce(3,"command_sec",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command_sec",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // command_sec ::= 
            { parser.Tree.reduce(0,"command_sec",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command_sec",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // more_cmd ::= more_cmd cmd cmd 
            { parser.Tree.reduce(3,"more_cmd",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("more_cmd",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // more_cmd ::= cmd cmd 
            { parser.Tree.reduce(2,"more_cmd",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("more_cmd",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // cmd ::= assignment 
            { parser.Tree.reduce(1,"cmd",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // cmd ::= equal 
            { parser.Tree.reduce(1,"cmd",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // assignment ::= ID EQ bool_expr S 
            { parser.Tree.reduce(4,"assignment",0);
              Object RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Boolean value = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                 parser.table.put(key,value);
                 System.out.println(key+" "+value);
           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // equal ::= EQUAL bool_expr actions_l 
            { parser.Tree.reduce(3,"equal",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("equal",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // bool_expr ::= bool_expr AND bool_expr 
            { parser.Tree.reduce(3,"bool_expr",0);
              Boolean RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Boolean x = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean y = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = x&y; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // bool_expr ::= bool_expr OR bool_expr 
            { parser.Tree.reduce(3,"bool_expr",0);
              Boolean RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Boolean x = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean y = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = x|y; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // bool_expr ::= NOT bool_expr 
            { parser.Tree.reduce(2,"bool_expr",0);
              Boolean RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean x = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = !x; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // bool_expr ::= RO bool_expr RC 
            { parser.Tree.reduce(3,"bool_expr",0);
              Boolean RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Boolean x = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = x; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // bool_expr ::= TRUE 
            { parser.Tree.reduce(1,"bool_expr",0);
              Boolean RESULT =null;
		 RESULT = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // bool_expr ::= FALSE 
            { parser.Tree.reduce(1,"bool_expr",0);
              Boolean RESULT =null;
		 RESULT = false; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // bool_expr ::= ID 
            { parser.Tree.reduce(1,"bool_expr",0);
              Boolean RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = parser.table.get(x); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // bool_expr ::= ANDFUNCTION RO bool_expr_l RC 
            { parser.Tree.reduce(4,"bool_expr",0);
              Boolean RESULT =null;
		int resleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int resright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Boolean res = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT=res; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // bool_expr_l ::= bool_expr_l CM bool_expr 
            { parser.Tree.reduce(3,"bool_expr_l",0);
              Boolean RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Boolean prev = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int currentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int currentright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean current = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  if(current.equals(false)){
                    RESULT = false;
                  }
                  else{
                    RESULT = true;
                  }
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr_l",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // bool_expr_l ::= bool_expr 
            { parser.Tree.reduce(1,"bool_expr_l",0);
              Boolean RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean x = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                 RESULT = x;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr_l",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // actions_l ::= actions_l NT0 action_instr 
            { parser.Tree.reduce(3,"actions_l",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("actions_l",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // actions_l ::= NT1 action_instr 
            { parser.Tree.reduce(2,"actions_l",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("actions_l",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // NT0 ::= 
            { parser.Tree.reduce(0,"NT0",0);
              Boolean RESULT =null;
		 RESULT = (Boolean) parser.stack(-1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT0",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT1 ::= 
            { parser.Tree.reduce(0,"NT1",0);
              Boolean RESULT =null;
		 RESULT = (Boolean) parser.stack(0); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT1",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // action_instr ::= TO bool_expr DO WRITE QSTRING S DONE 
            { parser.Tree.reduce(7,"action_instr",0);
              Object RESULT =null;
		int currentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int currentright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Boolean current = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                   Boolean prev = (Boolean) parser.stack(-7);
                   if(prev.equals(current)){
                    System.out.println(s);
                   }
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_instr",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
