
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 8;
  public static final int METERSECONDS = 17;
  public static final int PIPE = 15;
  public static final int M_CHAR = 16;
  public static final int CM = 10;
  public static final int S = 5;
  public static final int RO = 11;
  public static final int COL = 14;
  public static final int RC = 12;
  public static final int PRINT_WORD = 18;
  public static final int PART_WORD = 19;
  public static final int EOF = 0;
  public static final int SEP = 6;
  public static final int error = 1;
  public static final int ARROW = 13;
  public static final int EQ = 9;
  public static final int BO = 7;
  public static final int UINT = 21;
  public static final int QSTRING = 20;
  public static final int TK3 = 4;
  public static final int TK2 = 3;
  public static final int TK1 = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK1",
  "TK2",
  "TK3",
  "S",
  "SEP",
  "BO",
  "BC",
  "EQ",
  "CM",
  "RO",
  "RC",
  "ARROW",
  "COL",
  "PIPE",
  "M_CHAR",
  "METERSECONDS",
  "PRINT_WORD",
  "PART_WORD",
  "QSTRING",
  "UINT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("BC");
		TT[17]=new String("METERSECONDS");
		TT[15]=new String("PIPE");
		TT[16]=new String("M_CHAR");
		TT[10]=new String("CM");
		TT[5]=new String("S");
		TT[11]=new String("RO");
		TT[14]=new String("COL");
		TT[12]=new String("RC");
		TT[18]=new String("PRINT_WORD");
		TT[19]=new String("PART_WORD");
		TT[0]=new String("EOF");
		TT[6]=new String("SEP");
		TT[1]=new String("error");
		TT[13]=new String("ARROW");
		TT[9]=new String("EQ");
		TT[7]=new String("BO");
		TT[21]=new String("UINT");
		TT[20]=new String("QSTRING");
		TT[4]=new String("TK3");
		TT[3]=new String("TK2");
		TT[2]=new String("TK1");
	}
public String getTT(int i){return TT[i];}
}

